### PR TITLE
Populate key related attributes

### PR DESCRIPTION
**Pull request by mwielgoszewski**
This PR makes the following changes:

1. When creating a new private key object, a new certificate object, or setting a certificate on an existing private key object, populate the `CKA_PUBLIC_KEY_INFO` attribute with the respective public key value.
2. Include the following attributes and values when creating a private key object:

    * `CKA_TOKEN` (true)
    * `CKA_SENSITIVE` (true)
    * `CKA_ALWAYS_SENSITIVE` (true)
    * `CKA_NEVER_EXTRACTABLE` (true)
    * `CKA_ALWAYS_AUTHENTICATE` (false)
    * `CKA_UNWRAP` (false, not implemented)
    * `CKA_DERIVE` (false, not implemented)

3. ~Include the SHA1 hash prefix digest algorithm identifier used in RSA-PKCS mechanisms.~

Of the attributes listed in (2), `CKA_TOKEN` appears to be necessary for some tools to discover private keys associated with certificates, notably NSS. In my testing, I found NSS searches for respective private keys by the CKA_ID of the CKO_CERTIFICATE object and with a CKA_TOKEN attribute set to true.

### CODE REVIEW

**Comment by ericchiang** [comment]
Thanks for the change!

As the bot stated, we need the CLA check to pass to review your PR https://cla.developers.google.com/

**Comment by mwielgoszewski** [comment]
Hey @ericchiang, I saw that after I committed. I went and agreed to the CLA shortly after, however the workflow hasn't retriggered.

**Comment by ericchiang** [comment]
I retriggered but as still seeing errors:

https://github.com/google/go-p11-kit/pull/29/checks?check_run_id=9074400310

You may want to ensure the git commit is using the email you signed up with

**Comment by mwielgoszewski** [comment]
Thanks, I updated my author email address.

**Review by ericchiang — APPROVED** [review]
Thanks! lgtm other than the sha1 addition. Is there a reason this was included?

Our internal checks flag the use of that API. I realize the protocol layer (e.g. TLS) still needs to opt-into for that to be used, but would prefer to just not implement it

**Comment by mwielgoszewski** [comment]
@ericchiang the primary reason for including it was to pass `pkcs11-tool`'s [signature tests](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L6238) which uses SHA1. :/

**Comment by ericchiang** [comment]
Wonderful :)

Can we leave that out SHA1 now and work on passing pkcs11-tool's test suite later? If we're not running those tests as part of CI, it doesn't matter all that much for now.

I can open another issue to get more robust test suites into this repo

**Comment by ericchiang** [comment]
Thanks!

**Comment by mwielgoszewski** [comment]
Thanks @ericchiang, when you get a chance can you tag a release? Cheers.

**Comment by ericchiang** [comment]
https://github.com/google/go-p11-kit/releases/tag/v0.4.0

**Pull request merged**
